### ISSUE TITLE
Stagger and Stances Suggestion

### ISSUE THREAD

**Issue by yahi-ko** [CammiePone/Cammies-Combat-Tweaks#10]
how about adding menu for stances and adding staggers like Ghost of Tsushima?

**Comment by CammiePone** [comment]
would you be able to link some video references?

**Comment by CammiePone** [comment]
nvm someone else explained it. Yeah... I don't think those mechanics would work too great in Minecraft, especially the stagger mechanic. Any kind of combat-oriented mechanic that takes control away from another player is poor design, and just leads to players being frustrated (look at the Sandman in TF2 as an old example, McCree's stun grenade in Overwatch, etc).

They're fine in singleplayer games where the only things that get screwed by them are emotionless computers, but in multiplayer games, or games with multiplayer, it's a poor design choice.
