### ISSUE TITLE
Disabling Riptide out of water also disables it in water

### ISSUE THREAD

**Issue by NIKITAzed** [CammiePone/Cammies-Combat-Tweaks#11]
I forget the proper format for these

expected: riptide go zoom

what actually happens: it charges up and then just does nothing, like that one effect in cartoons when a laser or something charges up, gets ready to fire, and then you just hear that disappointing fart sound effect and it shows a tiny puff of smoke

love ur mod pls fix
may the poss be with you

**Comment by CammiePone** [comment]
Oh whoops, guess I should've seen that coming. Will fix, poss be with us all
