### ISSUE TITLE
[Server] Riptide outside of water still works after being disabled in config

### ISSUE THREAD

**Issue by NIKITAzed** [CammiePone/Cammies-Combat-Tweaks#12]
guess who's back, back again, shorty's back, tell a friend

edited combattweaks.json5
not sure if the 5 is meant to be there but that's how it generated

I mean it basically is what it is, if there is something obvious I missed then my bad, I did restart the server after changing the config.

**Comment by CammiePone** [comment]
I literally tested that wtf :despair:

**Comment by CammiePone** [comment]
Oh wait, uhhh try disabling it on your client too. Mojang did an oopsie there and, uhhhhh yeah. Riptide is all client-side

**Comment by NIKITAzed** [comment]
Yep, you're 100% right, that did it, that's weird, but fair enough I guess. 
(probably doesn't help that I used carpetmod to completely disable AntiCheat)
carry on
