### ISSUE TITLE
[Suggestion] Disable non-vanilla features in Multiplayer 

### ISSUE THREAD

**Issue by Soulplexis** [CammiePone/Cammies-Combat-Tweaks#16]
I got this mod because I wanted to play on a server and spam click without swinging constantly because manually timing attacks is annoying. but I used it and something about the mod seems to have tripped off the server's anticheat and they banned me. I'd like to be able to disable whatever it was that got me banned and just have the function where I can't swing before the cooldown is full

**Comment by CammiePone** [comment]
The only thing I can't disable is the swing speed changes, and that's probably what did it. Everything else that's handled client-side does require it to be on the server to function.

If all you want is a mod that lets you click without timing attacks, there's probably others out there for that.
