### ISSUE TITLE
Not able to attack after changing minimum attack cooldown

### ISSUE THREAD

**Issue by dull4h4n** [CammiePone/Cammies-Combat-Tweaks#17]
Combat delay seems incredibly fast. Attempted to adjust to make 1.5, lost all ability to use left or right click.
Changed to default it work.
Tried changing to whole number, still did not work.
Tried various numbers, did not work.

**Comment by CammiePone** [comment]
What's the number on the weapon in game

**Comment by CammiePone** [comment]
'cause it's entirely possible you set it to 0 or a negative, which would make it impossible to attack with that weapon. what you've provided me here tells me practically nothing about the issue. What weapon did you try and change it on, how did you go about making the datapack, etc

**Comment by dull4h4n** [comment]
I was using a stock iron sword, the variable on the mod for minimum weapon attack cooldown is 1.0 by default. I tried changing it to 1.5 to make it slower (if that is correct).

**Comment by CammiePone** [comment]
that is correct, yes. Can you send me your datapack?

**Comment by dull4h4n** [comment]
Not sure what you mean by datapack. No datapacks, but i do have various mods. Would the list of other mods help?

**Comment by dull4h4n** [comment]
Just to clarify, there was no crash, I simply lost the ability to use left or right click. I could no longer raise shield or interact with doors etc until I adjusted the variable back to its default 1.0.

**Comment by CammiePone** [comment]
...you modified the jar directly?

**Comment by dull4h4n** [comment]
Only the combattweaks.json5, and its currently at defaults. Only changed first line:
{
	"general": {
		"minAttackCooldown": 1.0,
		
... to 1.5.

**Comment by CammiePone** [comment]
That doesn't control swing speed 🤦

**Comment by dull4h4n** [comment]
Okay. So the only way to actually change would be to actually modify the jar then I take it. What would minattackCooldown changes do? Would it be possible for there to be a config setting to adjust the swing times to make them somewhere between current and vanilla?

**Comment by CammiePone** [comment]
So here's what you did: you told the game that the attack indicator has to be 150% charged before you can swing or right click with the weapon. The attack indicator never goes above 100% charged, so of course, nothing is gonna happen, including right click events.

If you want to modify swing speed, you need to make a datapack.
