### ISSUE TITLE
Attack speed changes are unconfigurable

### ISSUE THREAD

**Issue by RomanKnight** [CammiePone/Cammies-Combat-Tweaks#26]
It says in the mod description that every feature is configurable, but in fact the attack speed changes (one of the most major changes), along with other things, are not. I don't mind them on their own, but they cause balance issues when using weapons from other mods. It would be nice to have an option to disable.

**Comment by CammiePone** [comment]
one word: datapacks

**Comment by RomanKnight** [comment]
I actually did try to change it datapacks but couldn't to get it to work. It seemed like the changes implemented by the mod overrode anything the datapack could do. Maybe I was doing something wrong but I shouldn't have to research and create my own datapack to configure a feature that is advertised as being configurable by default. Why say "All the mod's features are configurable in-game through ModMenu" when they aren't?
