### ISSUE TITLE
Item cooldown does not affect attacking as well as right click.

### ISSUE THREAD

**Issue by PIRACYISTHEFT** [CammiePone/Cammies-Combat-Tweaks#5]
Tried it both with enderpearls and shields, I was able to attack and deal damage whilst in item cooldown.

**Comment by CammiePone** [comment]
With the items that were on cooldown?

**Comment by UpcraftLP** [comment]
item cooldown only affects right click, not left click. So this is just vanilla behavior.

**Comment by CammiePone** [comment]
Upcraft you fool. I changed it with CCT

**Comment by PIRACYISTHEFT** [comment]
> 
> 
> With the items that were on cooldown?

Nah with the sword in my righthand. I'm not going to attack someone with a shield or enderpearl.

**Comment by CammiePone** [comment]
Well then yeah, that's intended behaviour then. The cooldown mostly just applies for whenever you parry someone's weapon, making them unable to attack
